server:
  forward-headers-strategy: framework
ticket:
  port: 54975
  url: http://localhost:${ext.port}/
spring:
  cloud:
    gateway:
      routes:
      - id: tickets
        uri: ${ticket.url}
        predicates:
        - Path=/tickets/**
management:
  server:
    port: 8081
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
debug: true